### ISSUE TITLE
Translations don't work on UC Helper

### ISSUE THREAD

**Issue by egasparini** [yalla-coop/cost-of-living-support#201]
When I change the language on UC Helper e.g. to Italian, this is what I see:

![Image](https://user-images.githubusercontent.com/55511970/207856581-42cf4f23-4b5b-4890-8d97-0830896cbadf.png)

**Comment by egasparini** [comment]
Further feedback reported by @maggiehoughton:
- [ ] App title and welcome message do not translate [Notion issue #33](https://www.notion.so/yallacooperative/33-b72b0b5251d04f6e8d4ab6479bde53ee)
- [ ] Sometimes the copy at the bottom `What should I do once I am granted Universal Credit?` & its paragraph also aren't translated
- [ ] Some text disappears in different sections of the tool [Notion issue #34](https://www.notion.so/yallacooperative/34-c7121af3190c43f4b91f39b6c35844bd)
- [ ] Some text in accessibility section does not translate [Notion issue #35](https://www.notion.so/yallacooperative/35-fe4aac2c40fa4d0b958b53aeab483973)
- [ ] Tip box does not translate [Notion issue #36](https://www.notion.so/yallacooperative/36-2341b963056c444193c511ecaf0b1b28)

See screenshots in Notion, issues are linked next to each feedback item.
I also made a loom recording of some of these issues if that's helpful: https://www.loom.com/share/3c06a065cb8c463883fcfc205d309a3c

**Comment by remaininlight** [comment]
Translation to Italian is working for me on staging:
<img width="693" alt="image" src="https://user-images.githubusercontent.com/4106946/211383616-2b789bb1-4c17-44a4-acd1-fadacc231dde.png">

@egasparini What priority should we give deploying staging to production? UC helper production hasn't been updated since the start of the project so might have some complications

**Comment by egasparini** [comment]
@remaininlight and @cemalokten the initial issue of translating to Italian is fixed, but instead of creating a new task, since there were more issues with translations, I re-opened this one and added a comment above (see https://github.com/yalla-coop/cost-of-living-support/issues/201#issuecomment-1371011752) listing all the other things that are not working with translations - that I hadn't caught before, Maggie did. 
That's what needs looked at. Thank you!

**Comment by egasparini** [comment]
@cemalokten for sake of clarity, I'll close this issue and create a separate one about that 3rd item that's not checked off yet.
