### ISSUE TITLE
Create Issues + Product Roadmap

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/cost-of-living-support#49]
**Summary**
Here is an outline of actions we need to do to get ready to present the issues to Hyde on Tuesday

As this issue involves a few people, if you complete your action, unassign yourself and assign the next person, then update them in Discord. 

**Actions**
- [x] @egasparini  goes through the wireframes and writes up issues including key pieces of functionality. That has the links to figma
    - If Erica has any questions Jem can be on hand to answer
- [x] @jema28  to write the UI acceptance criteria with @fadeomar 
    - Describing the unseen functionality "When this is clicked, then this happens "
    - Rules if needed 
    - Character limits 
- [x] @thejoefriel  to add project lead context (important notes to consider for the client)
- [x] Issues go to @remaininlight and @RamyAlshurafa  where they can ask clarifying questions and size issues
- [x] @egasparini  takes issue to client for prioritisation
