### ISSUE TITLE
List components

### ISSUE THREAD

**Issue by jema28** [yalla-coop/cost-of-living-support#72]
### Template
- Link: 
- Prop names: 
- Criteria:
   - [x] Example

--

### Card / Section
- Link: https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4797%3A5634
- Prop names: 
- Criteria:
   - [x] Icon is 120px x 120px
   - [x] Each section has its own colour to distinguish them from each other. **Come back to this depending on the user testing colour comment**

--
### Card / Topic
- Link: https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4800%3A8396
- Prop names: https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4812%3A9455
- Criteria:
   - [x] **Note:** no border radius on this part of component in figma. The border radius is added to full component (Card / Topic + Card / Topic / Open): https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4800%3A11579
   - [x] **Variation 1:** 
       - 1 line (See more). The text is centre aligned with the text. Character limit: 24 characters
       - 1 line (See less) The text is top aligned with the text. Character limit: see above
   - [x] **Variation 2:**
      - 2 lines + (See more): The text is centre aligned with the text. Character limit: 68 characters
      - 2 lines + (See less): The text is top aligned with the text. Character limit: see above

### Card / Topic / Open
- Link: https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4800%3A8396
- Prop names: 
- Criteria:
   - [x] **Note**: no border radius on this component in figma. The border radius is added to full component (Card / Topic + Card / Topic / Open): https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4800%3A11579

--

### Card / Tip
- Link: https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4805%3A10019
- Prop names: https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4812%3A10144
- Criteria:
   - [x] Order of tips (can be found in the prop table): https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4805%3A10019
      - First topic: 1, 2
      - Second topic: 2, 3
      - Third topic: 3, 4
      - Fourth topic, 4, 1
      - Fifth topic: 1, 2
  - [x] Tips aren't collapsable 

### Header
- Link: https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4695%3A2059
- Prop names: https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4817%3A8781
- Criteria:
   - [x] Main header is Cost of living variation. The whitelabel variation includes their Primary colour and logo but with the same title (when they don't want to use the default gradient header) 

### Header / Section
- Link: https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4797%3A5458
- Prop names: https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4802%3A8720
- Criteria:
   - [x] 3 variations show in the prop table (Italic + Bold, Small italic + Bold, Bold)
   - [x] Responsiveness demo on mobile/tablet: ![Image](https://user-images.githubusercontent.com/25960351/200496162-5060d7e4-91af-4607-a6b9-f99afc1ba46b.gif)
   - [x] Character limit for Italic + Bold variation: 20 character. Each line (italics and bold) should only span one line and not wrap
  - [x] In mobile the text is centre aligned. In desktop the text is left aligned and is on one line instead of 2: https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4802%3A8720

### Button / Select language
- Link: https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4797%3A5956
- Prop names: https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4804%3A9471
- Criteria:
   - [x] Language name appears in native language #77 
   - [x] If there's no flag, the space is left empty #77

### Button / Select
- Link: https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4800%3A7666
- Prop names: https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4804%3A9892
- Criteria:
   - [x] Order of colours: Primary / Main, Secondary / Main, Tertiary / Main, Neutral / Main. If there's more, repeat the pattern

### Button / Section 
- Link: https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4810%3A8397
- Prop names: https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4810%3A13213
- Criteria:
   - [x] 3 variations:
      - Default (With reorder and hide)
      - Edit (added section)
      - Under review (without reorder and hide) 

### Social banner
- Link: https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4664%3A2037
- Prop names: https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4800%3A14646
- Criteria:
   - [x] Centre aligned in mobile and right aligned in desktop #50 

### Bar / Accessibility
- Link: https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4797%3A5752
- Prop names: https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4800%3A7925
- Criteria:
   - [x] Back button is visible on all pages apart from landing page

### Typography / Still need help
- Link: https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4797%3A5430

### Typography / Title, button, call
- Link: https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4812%3A8591
- Prop names: https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4812%3A8591

### Typography / Heading and links
- Link: https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4614%3A2047
- Example with three links: https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4806%3A8784

### Page section / Budgeting
- Link: https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4806%3A8693
- Prop names: https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4806%3A8721
- Criteria:
   - [x] Max width 1200px in desktop

### Page section / Detail and link inputs
- Link: https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4811%3A8571
- Prop names: https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4812%3A8661
- Criteria:
   - [x] Order of sections: Neutral - Light, Secondary - Light, repeat #59 

### Toggle
- Link: https://www.figma.com/file/LK8egFhosvyvR6jp8yPC31/Hyde-Design-system?node-id=4800%3A8438

**Comment by egasparini** [comment]
Typography styles and colour styles can be found here:

https://github.com/yalla-coop/cost-of-living-support/issues/67#issuecomment-1308355441

**Comment by fadeomar** [comment]
hey @jema28  on the header sections component variations about (small italic + bold) one, because the text is coming for the backend this will require more development work because now there is no way to determine if its regular italic or small italic and this will need more development time in both sides front and back what do you think?

**Comment by jema28** [comment]
Hey @fadeomar, it's just the 4 sub ones for Paying for housing that should be smaller. The rest are all the larger one. Does that make things easier?

**Comment by thejoefriel** [comment]
Hey @egasparini  @jema28 one to add to our post-sprint retro please - this issue being added in after we have sized all the issues and then also put in as a reference issue has caused a bit of confusion. Fadi has started working on this as a separate issue to implement the updates requested in this issue.

I think in future we need this component issue to be created before sizing (even if there's final edits to be made) and not a reference issue?

**Comment by thejoefriel** [comment]
PS I've asked @fadeomar to add a size to this issue once he's got a better idea, hopefully by lunch time. Fadi, please on size take into account time already spent + estimated time left to complete

**Comment by jema28** [comment]
Hey @thejoefriel sure thing, I'll keep this in mind for next time and have added to the notion retro board

**Comment by cemalokten** [comment]
- [ ] Button drag and drop has an large offset from the mouse, this is on Firefox.
https://user-images.githubusercontent.com/60609268/201914085-0db770cd-ed57-42ef-b16a-e187004afd51.mov

- [ ] Please check off and/or add relevant github issue links to all sections of this issue that are not checked off.
